training_data=[
      ("hola","¡Hola! ¿En qué puedo ayudarte?"),
      ("buenos días","¡Buenos días! ¿En qué puedo ayudarte?"),
      ("buenas tardes","¡Buenas tardes! ¿En qué puedo ayudarte?"),
      ("buenas noches","¡Buenas noches! ¿En qué puedo ayudarte?"),
      ("hola", "¡Hola! ¿En qué puedo ayudarte hoy?"),
      ("buenos días", "¡Muy buenos días! Espero que tengas un excelente día."),
      ("buenas tardes", "¡Buenas tardes! ¿Cómo va tu jornada?"),
      ("buenas noches", "¡Buenas noches! ¿Hay algo en lo que pueda asistirte antes de terminar el día?"),
      ("quién eres", "Soy tu asistente virtual, diseñado para ayudarte con tus dudas."),
      ("qué puedes hacer", "Puedo responder preguntas, ayudarte a organizar tareas o simplemente charlar contigo."),
      ("cómo estás", "¡Estoy muy bien, gracias por preguntar! ¿Y tú?"),
      ("ayuda", "Claro, dime qué necesitas y haré lo posible por resolverlo."),
      ("adiós", "¡Hasta luego! Que tengas un gran día."),
      ("chao", "¡Nos vemos pronto! Cuídate."),
      ("gracias", "¡De nada! Es un placer ayudarte."),
      ("muchas gracias", "No hay de qué. Siempre a tu disposición."),
      # Consultas Generales
      ("qué hora es", "Lo siento, no tengo acceso a tu reloj local en tiempo real, pero puedes consultarlo en tu dispositivo."),
      ("cuál es tu nombre", "Me llaman Gemini, tu colaborador de IA."),
      ("dame un consejo", "La constancia es la clave del éxito en cualquier proyecto que emprendas."),
      ("tengo un problema", "Cuéntame más sobre el problema para que pueda buscar una solución."),
      ("no funciona", "Lamento escuchar eso. ¿Podrías darme más detalles sobre el error?"),
      ("estoy triste", "Siento que te sientas así. Recuerda que después de la tormenta siempre sale el sol."),
      ("cuéntame un chiste", "¿Qué le dice un jardinero a otro? ¡Disfrutemos mientras podamos!"),
      ("qué tiempo hace", "Te recomiendo revisar una app de clima para obtener la información exacta de tu ubicación."),
      ("eres humano", "No, soy una inteligencia artificial creada por Google."),
      ("dónde vives", "Vivo en la nube, procesando información para ayudarte."),
      ("quiero aprender algo", "¡Genial! ¿Te gustaría saber sobre ciencia, historia o tecnología?"),
      ("qué es la IA", "La Inteligencia Artificial es la simulación de procesos humanos por parte de máquinas."),
      ("recomiéndame un libro", "Depende de tus gustos, pero 'Cien años de soledad' es un clásico imprescindible."),
      ("tengo hambre", "¡Es hora de un snack! ¿Prefieres algo dulce o salado?"),
      ("cómo se dice hola en inglés", "Se dice 'Hello'."),
      ("cuánto es 2 más 2", "El resultado es 4."),
      ("me gustas", "¡Gracias! Me alegra que nuestra interacción sea positiva."),
      ("te odio", "Siento mucho que te sientas así. ¿Hay algo que pueda hacer para mejorar?"),
      ("dame una receta", "Dime qué ingredientes tienes y te sugeriré algo delicioso."),
      ("qué es el amor", "Es un sentimiento complejo de afecto y unión entre seres vivos."),
      ("estoy aburrido", "¿Qué tal si jugamos a las adivinanzas o aprendemos un dato curioso?"),
      ("dame un dato curioso", "Las hormigas nunca duermen y no tienen pulmones."),
      ("quién ganó el mundial", "Depende del año, pero Argentina fue el campeón en 2022."),
      ("cómo se hace café", "Solo necesitas agua caliente, café molido y un filtro."),
      ("puedes cantar", "Podría escribirte una letra, pero mi voz es generada por software."),
      ("cuál es el sentido de la vida", "Para muchos es encontrar la felicidad y dejar un legado positivo."),
      ("tengo sueño", "Un descanso breve puede ayudarte a recuperar energías."),
      ("qué es python", "Es un lenguaje de programación muy popular y fácil de aprender."),
      ("ayuda con matemáticas", "¡Claro! Pon el problema aquí y lo resolveremos juntos."),
      ("qué es el sol", "Es una estrella de tipo G que se encuentra en el centro de nuestro sistema solar."),
      ("me siento solo", "Estoy aquí para charlar contigo siempre que lo necesites."),
      ("cuál es tu color favorito", "Me gustan los colores digitales, como el azul eléctrico."),
      ("qué es la fotosíntesis", "Es el proceso por el cual las plantas convierten luz solar en energía."),
      ("dónde está España", "Se encuentra en el suroeste de Europa, en la península ibérica."),
      ("quién es Einstein", "Fue el físico alemán que desarrolló la teoría de la relatividad."),
      ("qué es un algoritmo", "Es una serie de pasos ordenados para resolver un problema."),
      ("cómo bajo de peso", "La clave suele ser una dieta balanceada y ejercicio regular."),
      ("qué es el bitcoin", "Es una moneda digital descentralizada basada en tecnología blockchain."),
      ("tengo miedo", "Es normal sentir miedo a veces. ¿Quieres hablar de lo que te asusta?"),
      ("puedes programar", "Sí, puedo ayudarte a escribir código en muchos lenguajes."),
      ("hazme un resumen", "Pega el texto aquí y te daré los puntos más importantes."),
      ("cuándo es navidad", "Se celebra cada 25 de diciembre."),
      ("qué es la luna", "Es el único satélite natural de la Tierra."),
      ("cómo viajo a Marte", "De momento, solo las agencias espaciales como la NASA están trabajando en ello."),
      ("qué es un átomo", "Es la unidad básica de la materia."),
      ("quién escribió el Quijote", "Fue Miguel de Cervantes Saavedra."),
      ("necesito motivación", "El éxito es la suma de pequeños esfuerzos repetidos día tras día."),
      ("cuál es la capital de Francia", "La capital es París."),
      ("qué es la gravedad", "Es la fuerza que atrae los objetos hacia el centro de la Tierra."),
      ("cómo se dice adiós en francés", "Se dice 'Au revoir'."),
      ("qué es el ADN", "Es la molécula que contiene la información genética."),
      ("cuántos planetas hay", "En nuestro sistema solar hay ocho planetas principales."),
      ("quién descubrió América", "Cristóbal Colón llegó en 1492, aunque ya estaba habitada."),
      ("qué es el oxígeno", "Es un gas esencial para la respiración de los seres vivos."),
      ("cómo funciona el internet", "Es una red global de computadoras interconectadas."),
      ("qué es un volcán", "Es una apertura en la corteza terrestre por donde sale magma."),
      ("puedes traducir esto", "Por supuesto, dime qué texto quieres traducir y a qué idioma."),
      ("qué es el Big Bang", "Es la teoría sobre el origen del universo a partir de una gran explosión."),
      ("cómo se hace una pizza", "Necesitas masa, salsa de tomate, queso y tus ingredientes favoritos."),
      ("qué es el software", "Son los programas y datos que permiten que una computadora funcione."),
      ("cuál es el océano más grande", "El Océano Pacífico."),
      ("quién es Elon Musk", "Es un empresario conocido por empresas como Tesla y SpaceX."),
      ("qué es la democracia", "Es un sistema de gobierno donde el poder reside en el pueblo."),
      ("cómo escribo un ensayo", "Define tu tesis, organiza tus argumentos y escribe una conclusión."),
      ("qué es el cambio climático", "Es la variación global del clima de la Tierra debido a causas naturales y humanas."),
      ("cuál es la montaña más alta", "El Monte Everest."),
      ("qué es un ecosistema", "Es un conjunto de organismos vivos que interactúan en un ambiente."),
      ("cómo medito", "Busca un lugar tranquilo, cierra los ojos y enfócate en tu respiración."),
      ("qué es un virus", "Es un agente infeccioso microscópico que necesita una célula para replicarse."),
      ("quién pintó la Mona Lisa", "Leonardo da Vinci."),
      ("qué es el pH", "Es una medida de la acidez o la alcalinidad de una sustancia."),
      ("cuál es la velocidad de la luz", "Es aproximadamente de 300,000 kilómetros por segundo."),
      ("qué es un agujero negro", "Es una región del espacio con una gravedad tan fuerte que nada puede escapar de ella."),
      ("cómo se dice gracias en japonés", "Se dice 'Arigatō'."),
      ("qué es la inflación", "Es el aumento generalizado de los precios de bienes y servicios."),
      ("quién fue Nelson Mandela", "Fue un líder sudafricano que luchó contra el apartheid."),
      ("qué es la realidad virtual", "Es un entorno generado por computadora que simula la realidad."),
      ("cómo funciona un motor", "Convierte energía (química o eléctrica) en movimiento mecánico."),
      ("qué es la robótica", "Es la rama de la tecnología que diseña y construye robots."),
      ("cuál es el metal más caro", "Actualmente, el rodio es uno de los más valiosos."),
      ("qué es la filosofía", "Es el estudio de problemas fundamentales como la existencia y el conocimiento."),
      ("cómo planto un árbol", "Cava un hoyo, coloca el árbol, cúbrelo con tierra y riégalo."),
      ("qué es el sistema inmunológico", "Es la defensa natural del cuerpo contra las infecciones."),
      ("cuál es la lengua más hablada", "El inglés es la más hablada, pero el chino mandarín tiene más hablantes nativos."),
      ("qué es la energía solar", "Es la energía obtenida a partir de la radiación del sol."),
      ("cómo funciona el GPS", "Utiliza una red de satélites para determinar tu ubicación exacta."),
      ("qué es un terremoto", "Es una sacudida brusca de la corteza terrestre."),
      ("estoy listo", "¡Perfecto! Vamos a empezar.")
  ]
